### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sarah872** [OluwadareLab/HiC-GNN#2]
Hi,

thanks for this tool!
Could you please list the requirements that I need to install? I installed so far numpy and ge, but I'm getting an error because of the line `from ge import LINE`:
```
$ python3 HiC-GNN_main.py
Traceback (most recent call last):
  File "/scratch/gnn/HiC-GNN/HiC-GNN_main.py", line 2, in <module>
    from ge import LINE
ImportError: cannot import name 'LINE' from 'ge' (/scratch/gnn/conda_gnn/lib/python3.11/site-packages/ge/__init__.py)
```

Also, what other modules do I need to install?

**Comment by OluwadareLab** [comment]
Thanks for using our tool. We propose the two solutions below to address your questions:
**1)** The easiest solution of course is that you can [use the Docker-containerized environment setting for running HiC-GNN](https://github.com/OluwadareLab/HiC-GNN) that we have provided. We believe this approach is straightforward, saves your time, and also makes the software ready to use without dealing with dependency issues. 

**2)** **Now to the other solution that directly answers your question**. To list all installed packages in our current HiC-GNN environment from a Python console using pip, we utilized the following script:
`>>> import pkg_resources
installed_packages = pkg_resources.working_set
installed_packages_list = sorted(["%s==%s" % (i.key, i.version)
   for i in installed_packages])
print(installed_packages_list)`

**The output list below shows all the modules we installed in the HiC-GNN python environment with the versions**. Please note that we likely used one or more of these modules in the code.

`['absl-py==0.13.0', 'astor==0.8.1', 'cached-property==1.5.2', 'certifi==2021.5.30', 'charset-normalizer==2.0.4', 'cycler==0.10.0', 'decorator==5.0.9', 'fastdtw==0.3.2', 'gast==0.2.2', 'ge==0.0.0', 'gensim==3.6.0', 'google-pasta==0.2.0', 'googledrivedownloader==0.4', 'grpcio==1.39.0', 'h5py==3.3.0', 'idna==3.2', 'importlib-metadata==4.6.3', 'isodate==0.6.0', 'jinja2==3.0.1', 'joblib==1.0.1', 'keras-applications==1.0.8', 'keras-preprocessing==1.1.2', 'kiwisolver==1.3.1', 'markdown==3.3.4', 'markupsafe==2.0.1', 'matplotlib==3.4.2', 'networkx==2.6.2', 'numpy==1.21.1', 'opt-einsum==3.3.0', 'pandas==1.3.1', 'pillow==8.3.1', 'pip==21.2.2', 'protobuf==3.17.3', 'pyparsing==2.4.7', 'python-dateutil==2.8.2', 'python-louvain==0.15', 'pytz==2021.1', 'rdflib==6.0.0', 'requests==2.26.0', 'scikit-learn==0.24.2', 'scipy==1.7.1', 'setuptools==57.4.0', 'six==1.16.0', 'smart-open==5.1.0', 'tensorboard==1.15.0', 'tensorflow-estimator==1.15.1', 'tensorflow==1.15.2', 'termcolor==1.1.0', 'threadpoolctl==2.2.0', 'torch-cluster==1.5.9', 'torch-geometric==1.7.2', 'torch-scatter==2.0.8', 'torch-sparse==0.6.11', 'torch-spline-conv==1.2.1', 'torch==1.9.0', 'tqdm==4.62.0', 'typing-extensions==3.10.0.0', 'urllib3==1.26.6', 'werkzeug==2.0.1', 'wheel==0.36.2', 'wrapt==1.12.1', 'zipp==3.5.0']`

Also, note that our python version (`>>> print (sys.version)`) is:
`3.7.11 (default, Jul  3 2021, 17:58:19) 
[GCC 9.3.0]`

We hope that these solutions sufficiently address your question. Thanks.
