### ISSUE TITLE
Inputs to HiC-GNN_main.py 

### ISSUE THREAD

**Issue by LNGDingj** [OluwadareLab/HiC-GNN#3]
Hello, @OluwadareLab 

I am interested in applying HiC-GNN to our HiC data.

Could you explain more about the requirement of input files to HiC-GNN_main.py? Does the input matrix need normalization or not?
If I extract input matrix of contact map from .hic files generated by Juicer using juicer_tools dump, should I use "`juicer_tools dump observed NONE xxxxxxxx.hic ...`" (without normalization)? Or I need choose a normalization method from "VC/VC_SQRT/KR"

Thanks so much for your helps!

**Comment by vhovenga** [comment]
Hello @LNGDingj,

Thank you for your inquiry. HiC-GNN_main.py automatically normalizes the input map, so you should use a map that is not normalized.

**Comment by LNGDingj** [comment]
Hi @vhovenga, 

Thank you very much for quick reply.

It will be very helpful for HiC-GNN users if you could describe the general procedures/methods that you suggest to extract un-normalized map from .hic file to prepare input files for HiC-GNN.

Since the HiC-GNN example input file '**HiC-GNN/Data/GM12878_500kb_chr19_list.txt**' looks like normalized observations 
 
![image](https://user-images.githubusercontent.com/53267778/216706623-c4b00433-600e-4ad1-899d-c77197c15096.png)

Here is the list with **un-normalized observed** contact map I extracted using _juicer_tools dump_ looks as
```
0       0       16668.0
0       500000  5072.0
500000  500000  47417.0
0       1000000 763.0
500000  1000000 8633.0
1000000 1000000 47882.0
0       1500000 555.0
500000  1500000 1915.0
1000000 1500000 9315.0
1500000 1500000 56276.0
```

And the list with **normalized observed** contact map I extracted using _juicer_tools dump_ looks as
```
0       0       72921.195
0       500000  12287.082
500000  500000  63606.688
0       1000000 1852.7592
500000  1000000 11607.946
1000000 1000000 64534.34
0       1500000 1193.6244
500000  1500000 2280.5662
1000000 1500000 11119.409
1500000 1500000 59497.996
```

**Comment by vhovenga** [comment]
@LNGDingj The example data was downloaded from the GSDB database: http://gsdb.mu.hekademeia.org/. I believe these maps were normalized using Yaffe and Tanay normalization technique. Our pipeline renormalizes the input data to the interval [0,1] using KR normalization for the training of the neural network. Because of this renormalization, it is possible to use either non-normalized maps or normalized maps for the input.

**Comment by LNGDingj** [comment]
@vhovenga Thanks a lot for the detailed explanations.
